### PR TITLE
Update BossSkills.yml

### PR DESCRIPTION
**Pull request by Bapus77**
It’s an orbital laser. Might be cool.

### CODE REVIEW

**Comment by SXRWahrheit** [comment]
Thanks for the proposed contribution! I'm not currently accepting PRs to this repository because I both don't have a Contributors' License Agreement set up yet and because I'm planning major rewrites following the completion of my current server project. In accordance with the license, you may copy these files for use on your server and modify them as you please **_as long as you do not accept any payments or donations_** and provide credit to me for the originals.

I don't currently have a timeframe for the planned updates, but feel free to watch the repository to see changes as they come!

**Comment by Bapus77** [comment]
Hey man, I dont do servers that much, and wouldn’t dream of not giving
credit. It’s fraud, and I think of myself as an honest person. But please,
if I can do anything for you, or anything to help you with these rewrites,
email me back. Also feel free to use my laser thingie.

Thanks for the email, and hope you have a great day :)

**Comment by SXRWahrheit** [comment]
Thanks! <3

**Comment by Bapus77** [comment]
Hey, do you have discord, and if so, can I add you?

Appreciated

**Comment by Bapus77** [comment]
Hey, one more thing: could I use some of your code in my stuff. Ill credit
you completely for your work, but I would still appreciate it.

Thanks again

**Comment by Bapus77** [comment]
Here is just a bit of what I’ve been working on: feedback would be
appreciated:)

Skills:
- Skill{s=Hellgift} @Self >700 0.1
- Skill{s=UnholyBrigade} @Target =100
- Skill{s=LucifersRage} @PIR{r=10} >400 0.05
- Skill{s=SinningTornado} @Self <650 0.05
- Skill{s=UndeadSpike} @Target =400
- Skill{s=DeathsPull} @PIR{r=20} 0.05
- Skill{s=SinnersGrace} @Self ~onTimer: 800
- Skill{s=Overlord} @Target ~onTimer: 400 0.1
- Skill{s=GrimacingScythe} @Target 0.1
Hellgift
Skills:
- potion{type:INSTANT_HEALTH;d=1;l=10} @Self
- potion{type:INCREASE_DAMAGE;d=50;l=50} @Self
- effect:particles{particle=flame;a=50;hs=0.2;vs=0.8;y=1;s=0.1}
- sound{entity.end.rod} @Self
- Skill{s=Combust} @Self
Combust
Skills:
- sound{block.tnt.explode} @Self
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
- delay 1
- effect:particles{particle=flame;a=100;hs=0.1;vs=1;s=0.05} @Self
DeathRings
Skills:
- message{m="<mob.name><&co> All those who are near me..."}
@PlayersInRadius{r=40}
- message{m="<mob.name><&co> DIE"} @PlayersInRadius{r=40}
-
effect:particlering{particle=reddust;radius=1;points=32;amount=1;hS=1;vS=0;color=#AA0000}
@self
- ignite{d=100;r=1}
- damage{ia=true;a=5;r=1}
- delay 1
-
effect:particlering{particle=reddust;radius=1.5;points=48;amount=1;hS=1;vS=0;y=0.1;color=#AA0000}
@self
- ignite{d=100;r=1.5}
- damage{ia=true;a=5;r=1.5}
- delay 1
-
effect:particlering{particle=reddust;radius=2;points=64;amount=1;hS=1;vS=0;y=0.3;color=#AA0000}
@self
- ignite{d=100;r=2}
- damage{ia=true;a=5;r=2}
- delay 1
-
effect:particlering{particle=reddust;radius=2.5;points=80;amount=1;hS=1;vS=0;y=0.5;color=#AA0000}
@self
- ignite{d=100;r=2.5}
- damage{ia=true;a=5;r=2.5}
- delay 1
-
effect:particlering{particle=reddust;radius=3;points=96;amount=1;hS=1;vS=0;y=0.8;color=#AA0000}
@self
- ignite{d=100;r=3}
- damage{ia=true;a=5;r=3}
- delay 1
-
effect:particlering{particle=reddust;radius=3.5;points=112;amount=1;hS=1;vS=0;y=1.1;color=#AA0000}
@self
- ignite{d=100;r=3.5}
- damage{ia=true;a=5;r=3.5}
- delay 1
-
effect:particlering{particle=reddust;radius=4;points=128;amount=1;hS=1;vS=0;y=1.4;color=#AA0000}
@self
- ignite{d=100;r=4}
- damage{ia=true;a=5;r=4}
- delay 1
-
effect:particlering{particle=reddust;radius=4.5;points=128;amount=1;hS=1;vS=0;y=1.4;color=#AA0000}
@self
- ignite{d=100;r=4.5}
- damage{ia=true;a=5;r=4.5}
- delay 1
-
effect:particlering{particle=reddust;radius=5;points=128;amount=1;hS=1;vS=0;y=1.4;color=#AA0000}
@self
- ignite{d=100;r=5}
- damage{ia=true;a=5;r=5}
- delay 1
-
effect:particlering{particle=reddust;radius=5.5;points=128;amount=1;hS=1;vS=0;y=1.4;color=#AA0000}
@self
- ignite{d=100;r=5.5}
- damage{ia=true;a=5;r=5.5}
- delay 1
-
effect:particlering{particle=reddust;radius=6;points=128;amount=1;hS=1;vS=0;y=1.4;color=#AA0000}
@self
- ignite{d=100;r=6}
- damage{ia=true;a=5;r=6}
BackHand
Skills:
- teleport @PIR{r=10;limit=1}
- effect:particles{p=explosion_medium;a=15} @EIR{r=5;limit=1}
- effect:particles{p=crit_magic;amount=2;y=1.5} @self
- damage{a=7} @PIR{r=10;limit=1}
- sound{s=entity.ghast.shoot} @self
- sound{s=entity.ghast.shoot} @self
- sound{s=entity.ghast.shoot} @self
UnholyBrigade
Skills:
-
effect:particles{particle=cloud;a=70;mr=10;y=1.5;vs=0.1;hs=0.2;s=0.8;fo=0.2;so=0.2;d=5}
@Self
- damage{a=10}
- Skill{s=DeathylGlance} @Target
- Skill{s=Earthquake} @PIR{r=7}
- Skill{s=SummonLesserFiend} @Self
DeathlyGlance
Skills:
- projectile{i=1;oT=DGTick;oH=DGHit;mr=30;tyo=0.9;sE=false;v=75} @Target
- effect:particles{particle=dragon_breath;a=100;y=0;vs=0.5;hs=0.2;s=0.5}
@Target
Earthquake
Skills:
- effect:particles{particle=end_rod;a=100;y=0;vs=0.2;hs=0.2;s=0.5} @Self
- damage{a=10;ia=true} @PIR{r=7}
-
effect:particletornado{p=falling_dust;cp=largeexplode;mr=2.2;h=4;i=4;d=100;rs=1;sh=1;cs=0;ca=0;chs=0.1;cvs=0.1;cps=1;cyo=2}
@Self
- potion{type=DAMAGE_RESISTANCE;d=100;l=6} @Self
SummonLesserFiend
Skills:
- summon{type=Lesser_Fiend;r=5;a=5;yr=0} @Self
- sound{entity.baby.zombie.growl} @Self
Overlord
Skills:
- Skill{s=Laser} @Target
Laser:
Skills:
- projectile{i=1;oT=LaserTick;oH=LaserHit;oE=LaserEnd;mr=5;sE=false;v=100}
@Target
LaserTick:
Skills:
- effect:particlering{p=flame;r=5;points=40} @origin
- effect:particles{particle=totem;a=20;s=0.5;hs=0.1;vs=0.1} @origin
- delay 20
LaserHit:
Skills:
- damage{ia=true;a=20;pkb=true}
- ignite{t=100}
- effect{effect=Black_Screen;d=10} @Target
- stun{d=100;f=true} @origin
- effect:explosion @PIR{r=10}
- damage{a=30;pkb=false}
LaserEnd
Skills:
- Skill{s=Overlord2} @PIR{r=20}
Overlord2
Skills:
- effect{effect=enderbeam;d=5} @PIR{r=20}
- damage{ia=true;a=2}
- Skill{s=FireballBarage} @PIR{r=20}
FireballBarrage:
Skills:
- shootfireball{y=1.3;v=40} @target
- damage{a=5;pkb=true}
- ignite{t=100}
- delay 10
- shootfireball{y=1.3;v=40} @target
- damage{a=5;pkb=true}
- ignite{t=100}
- delay 10
- shootfireball{y=1.3;v=40} @target
- damage{a=5;pkb=true}
- ignite{t=100}
LucifersRage:
Skills:
- effect:particles{particle=reddust;a=50;hs=1;vs=0.2;y=0} @Self
- delay 10
- ignite{d=300} @PIR{r=5}
- message{m="<mob.name><&co> Burn, begone back into the filth of this
planet that gave birth to your kind."} @PlayersInRadius{r=40}
- sound{s=entity.zombie.growl} @Self
- sound{s=entity.ghast.shoot} @Self
- Skill{s=DemonicBurn} @Target
DemonicBurn
Skills:
-
effect:particleline{p=flame;a=1;fo=true;points=40;s=0;hs=5;vs=0.4;tyo=1.5;xo=3;y=1.5}
@Self
- ignite{d=50}
- damage{a=20}
-
effect:particleline{p=flame;a=1;fo=true;points=40;s=0;hs=0.4;vs=5;tyo=1.5;xo=3}
@Self
- ignite{d=50}
- damage{a=20}
- effect:enderbeam;p=crit_magic;a=50;s=1;hs=0.3;vs=0.8;y=1.3} @Target
- ignite{d=120}
- damage{a=20;pkb=true}
- effect:geyser{type=LAVA;height=10;speed=15} @Target
- ignite{d=175}
- damage{ia=true;a=1.5;pkb=true}

**Pull request closed without merging**
